### PR TITLE
implement serde_json export/import

### PR DESCRIPTION
**Pull request by gin66**
In order to use trained SOMs for later use, I have had the need for import/export.
Using serde I have implemented json as import/export format. One simple test added under tests/.

If you like it, you can include it in mainstream.

While I was at it, I have added Edition 2008 in Cargo.toml and fixed the one or other compiler warning.

### CODE REVIEW

**Review by avinashshenoy97 — CHANGES_REQUESTED** [review]
Maybe up our release version in the manifest (and the badge in readme) from "1.0.0" to "1.1.0" or even "2.0.0" ?

**Comment by gin66** [comment]
if I understand semantic versioning correctly for this being just an addition to the API, then it should be 1.1.0. Will update later, when I have access to my computer.

**Comment by avinashshenoy97** [comment]
Exactly.

**Comment by gin66** [comment]
The master branch has been updated. No idea, if this is automatically added to the original pull request. Please check

**Review by avinashshenoy97 — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
