### PR TITLE
Add lint and formatting checks to CI

### PR DESCRIPTION
**Pull request by JayKickliter**
This PR adds two new CI steps: one to check formatting (rustfmt), and another to check for code lints (clippy).

I reformatted the code and fixed all lints. However, I purposely introduced one lint and formatting mistake to ensure the CI steps execute as expected. If these changes are desirable, I will remove the last commit so this PR can merge.

### CODE REVIEW

**Comment by JayKickliter** [comment]
For some reason Travis isn't building this PR. I'm guessing that the setting to build PRs is not turned on for this repo?

**Comment by JayKickliter** [comment]
Disregard my last comment, it is [building](https://travis-ci.org/github/avinashshenoy97/RusticSOM/jobs/731763000#L333-L376). Travis CI integration doesn't seem to be enabled for this repo, so for what it's worth, there is nothing stopping you from accidentally merging failing code.

**Comment by avinashshenoy97** [comment]
Had to reauthorise. Happy to merge if you undo the last commit and push again.

Thanks.

**Comment by JayKickliter** [comment]
> undo the last commit and push again

Done. Thanks!

**Pull request merged**
